apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: book2go
type: Opaque
data:
  POSTGRES_DB: YjJnX2Ri # "b2g_db" in base64
  POSTGRES_USER: dXNlcg==       # "user" in base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # "password" in base64