apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: book2go
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=       # "user" in base64
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q= # "password" in base64