server:
  port: 8090

spring:
  application:
    name: auth-service

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: REDACTED
            clientSecret: REDACTED
            scope:
              - user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          google:
            clientId: REDACTED
            clientSecret: REDACTED
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

  datasource:
    url: jdbc:postgresql://localhost:5432/b2g_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost # Per test locale fuori da Docker
    port: 5672
    username: guest
    password: guest


services:
  restaurant:
    url: http://localhost:8091
  accounting:
    url: http://localhost:8092

logging:
  level:
    root: INFO
    com.b2g.authservice: DEBUG

jwt:
  secret: mySecretKey
  expiration-ms: 3600000