services:
  postgres:
    image: postgres:15
    container_name: pg-b2gdb
    environment:
      POSTGRES_DB: b2g_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - b2g-net

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # AMQP (per i microservizi)
      - "15672:15672"   # Management UI (visita http://localhost:15672)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - b2g-net

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_container
    ports:
      - "1025:1025"     # SMTP server (per Spring Boot)
      - "8025:8025"     # Web UI (visita http://localhost:8025)
    networks:
      - b2g-net

volumes:
  pg_data:
  rabbitmq_data:

networks:
  b2g-net:
    driver: bridge