spring:
  application:
    name: recommendation-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: guest12345
    pool:
      max-connection-pool-size: 100
      max-connection-lifetime: 1800000
      connection-acquisition-timeout: 5000
  data:
    neo4j:
      database: neo4j
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    dynamic: true

# Server Configuration
server:
  port: 8096

# authentication
authService:
  internal:
    url: http://localhost:8090/internal

# Logging
logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework.amqp.rabbit: DEBUG

# rabbitMq configurations
app:
  rabbitmq:
    exchange: b2g.topic.exchange
    service:
      prefix: recommendation
    bindingkey:
      book:
        creation: book.created