spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/b2g_library
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true

# authentication
authService:
  internal:
    url: http://localhost:8090
  jwks:
    url: http://localhost:8090/auth/.well-known/jwks.json

jwt:
  public-key:
    cache:
      seconds: 300

# Server Configuration
server:
  port: 8095

app:
  rabbitmq:
    exchange: b2g.topic.exchange
    bindingkey:
      book:
        format:
          created: book.format.created
      lend:
        request:
          created: lend.request.created
    routingkey:
      lend:
        book:
          reserved: lend.book.reserved
      availability:
        available: book.availability.available
        low: book.availability.low
        out: book.availability.out
        not_available: book.availability.not_available