spring:
  application:
    name: lend-service
  datasource:
    url: jdbc:postgresql://localhost:5432/b2g_rental
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true

# Server Configuration
server:
  port: 8099

# authentication
authService:
  internal:
    url: http://localhost:8090
  jwks:
    url: http://localhost:8090/auth/.well-known/jwks.json

jwt:
  public-key:
    cache:
      seconds: 300

catalogService:
  internal:
    url: http://localhost:8091/books/
inventoryService:
  internal:
    url: http://localhost:8095/inventory/
subscriptionService:
  internal:
    url: http://localhost:8098/subscriptions/readerUUID

# Logging
logging:
  level:
    com.b2g.catalogservice: DEBUG
    org.springframework.security: DEBUG

# rabbitMq configurations
app:
  rabbitmq:
    exchange: b2g.topic.exchange
    queue:
      name: rental
    routingkey:
      lend:
        request:
          created: lend.request.created
        ready: lend.ready
        created: lend.created
        failed: lend.failed
        ended: lend.ended
      reservation:
        created: reservation.created
        failed: reservation.failed
    bindingkey:
      book:
        reserved: lend.book.reserved