apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: book2go
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432          # porta interna
      targetPort: 5432    # porta del container
      nodePort: 30042     # porta esterna visibile da host
  type: NodePort