spring:
  application:
    name: review-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/b2g_reviews}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: ${SPRING_DATASOURCE_HIKARI_INIT_TIMEOUT:-1}
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONN_TIMEOUT:30000}
      validation-timeout: ${SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT:5000}
      idle-timeout: ${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT:600000}
      max-lifetime: ${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME:1800000}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

# Server Configuration
server:
  port: ${SERVER_PORT:8097}

# authentication
authService:
  internal:
    url: ${AUTH_SERVICE_INTERNAL_URL:http://auth-service:8090/internal}

# RabbitMQ configurations
app:
  rabbitmq:
    exchange: ${APP_RABBITMQ_EXCHANGE:b2g.topic.exchange}
    service:
      prefix: ${APP_RABBITMQ_SERVICE_PREFIX:review}
    binding-key:
      review:
        authorized: ${APP_RABBITMQ_BINDINGKEY_REVIEW_AUTHORIZED:review.reader.ownership.checked}
      # review.rejected: ${APP_RABBITMQ_BINDINGKEY_REVIEW_REJECTED:review.rejected} # commented out
    routing-key:
      review:
        authorization:
          requested: ${APP_RABBITMQ_ROUTINGKEY_REVIEW_AUTH_REQUESTED:reader.ownership.requested}
      rating:
        updated: book.rating.updated
